### ISSUE TITLE
Strips alway turn on at 100% brightness

### ISSUE THREAD

**Issue by moekdegroot** [kasteleman/com.innr#4] opened 2017-11-18 10:58 UTC
Hi @kasteleman 

If I set the strips for example at 50% in the mobile card, turn them off (clicking on the left side of the mobile card) and them click them on again, the brightness level of 50% isn't applied.
Even though the slider in the mobile card is still at 50% the lights switch on with 100% brightness.
Tweaking the slider a little bit to the left or right makes the strips jump to the lower brightness.
Any ideas?

Thanks, Moek

**Comment by kasteleman** [comment] 2017-11-18 11:00
Hi Moek,

thx for reporting.
Can you tell me how "old" the strips are, or did you buy them recently.
There is a issue in the firmware for the older strips, but don't know if that is the case now.

Regards,

Martin

**Comment by moekdegroot** [comment] 2017-11-18 11:46
I guess thats whats the case.
Had them lying around for at least a year, maybe even two :)
Is there anything that can be done about it?
Do you need need perhaps more device info or something?

**Comment by kasteleman** [comment] 2017-11-18 22:32
I can confirm it is a firmware bug for both devices.
There may be a workaround by rewriting the on off part for the devices. Will have a look. Only thing is, I don't own those devices, so can't test the code myself.

I get back to you as soon as I've adapted the code.

**Comment by kasteleman** [comment] 2017-11-20 08:54
Having Some troubles with implementing the workaround. I’m in contact with Athom to check how we can fix this. Also asked INNR if a firmware update is an option

**Comment by moekdegroot** [comment] 2017-11-20 13:11
Hi Martin,

Thank you very much for looking into this.
Also searched the web for some sort of possibility to upgrade but couldn't find anything.
I have another box with a strip on, I guess, the old firmware.
If it makes the coding easier I can send it to you if you like?

**Comment by kasteleman** [comment] 2017-11-20 13:20
Hi, let’s wait a little until I get some answers.
I’ll get back to you as soon as possible

**Comment by kasteleman** [comment] 2017-11-21 17:53
Got some detailed information from INNR support. A Ota firmware isn't a option. In theory you could open the device and connect a flat cable and flash it. So the software option is the way to go. It's going to take some extra time to implement and also need support from Athom. So don't expect a solution within a few days. It's hard to give a timeline for it, nor do I know if it can be done within Homey.

**Comment by moekdegroot** [comment] 2017-11-21 18:52
Thanks for investigating Martin. 
Bummer about the firmware but can’t say I’m surprised. 
And please take your time. 
My workaround (setting a brightness level in a flow instead of just turning it on) is more than sufficiant for now. 
Let me know if you need anything tested. 
Cheers!
Moek

**Comment by kasteleman** [comment] 2017-11-27 21:36
Hi Moek,

can you contact me on slack?
So we could walk through some steps involving possible fixes?

**Comment by kasteleman** [comment] 2017-11-28 09:31
Updated the beta branch with a possible fix for the PL 110. Don’t own the PL 110, so can not verify if it fixes the problem or brakes something. Beware of that when testing!

**Comment by moekdegroot** [comment] 2017-11-28 09:48
Hi Martin,

As soon as I saw your new commit this morning I immediately installed it and when I wanted to report my findings saw your latest post...
But, I think you did it! At least for the pucks.
Even though zigbee is really, really, really acting up because I'm on 1.5.5 the pucks are keeping their dimmed state when I turn them off and on again.
The strips however keep turning on at 100%.
The pucks were working as soon as I installed the app but I removed and re-added the lights just to be safe and they kept working.
I also removed the strips to see if after a repair the dimming would stick but that didn't work.
Do you still want to hook up on slack?
Thanks again!
Moek

**Comment by moekdegroot** [comment] 2017-11-28 10:12
By the way, bought you a couple of beers/coffees for your trouble.

**Comment by kasteleman** [comment] 2017-11-28 10:12
Hi Moek.

No need to hook up on slack then.
Thx for testing.
It is correct that the fix is only applied to the pucks. I will update the driver for the led strips this evening and you can test them as well.

After that I can publish it to the App Store.

Thx for the feedback!

**Comment by kasteleman** [comment] 2017-11-28 10:14
Wow thx Moek for the donation. that wasn’t necessary, but very appreciated

**Comment by moekdegroot** [comment] 2017-11-28 10:18
No problem at all Martin!
I'll keep an eye out for the fix and will let you know the outcome.

**Comment by kasteleman** [comment] 2017-11-28 19:29
Hi Moek. Updated the beta branch, can you test?

**Comment by moekdegroot** [comment] 2017-11-28 19:32
Off course!
Will install now and report back in a bit.
Just a heads up.
I take it you didn't change anything for the pucks right?
I have them in the hall where my daugther sleeps so can't test them :)

**Comment by kasteleman** [comment] 2017-11-28 19:35
the pucks should be alright...but hé it is beta ;-)

**Comment by moekdegroot** [comment] 2017-11-28 19:40
Well, for a beta it's working supreme!
The strips also work flawless.
Nice job Martin!
Thanks very much, happy camper overhere :)

**Comment by kasteleman** [comment] 2017-11-28 19:42
wow, that was quick!
Small question:
Did you test the dimming part also?

**Comment by moekdegroot** [comment] 2017-11-28 19:51
Off course.
I dragged that slider all over the place :)
The brightness is very reaktive and is remembered after turning it of and on, both via the device card and via a flow.
I just realised I didn't test if changing the brightness with a flow also works.
Hang on.

**Comment by moekdegroot** [comment] 2017-11-28 19:59
Ok, not a showstopper but:
If the strip was turned off when it was at 100% and I start a flow that sets the brightness to for example 25% the strip first jumps to 100% and then to 25%.
I can imagine that a flow like that for the middle of the night is less effective because it creates a flash when the light gets turned on.
The same for visa versa. Which is less "annoying" because it's like a delayed dimming up.

**Comment by kasteleman** [comment] 2017-11-28 20:06
hmm, that was not a issue before I applied the fix?
What card did you use within the flow to change the brightness? Because there are 2 cards you can use: change brightness and change related brightness. Not sure if it makes any difference...

**Comment by moekdegroot** [comment] 2017-11-28 20:14
To be honest, I didn't check that with your previous fix either... sorry.
And iIt happens with both cards.
And now I even starting to doubt if ever saw my workaround in action.
I created the flow for my wife who is always the first one up.
You want me to revert to the appstore version and double check?

**Comment by moekdegroot** [comment] 2017-11-28 20:19
Just installed the appstore version and in that version it is working so it was introduced with your first or second fix.
I also have the first fix on my computer so I'll check that as well

**Comment by kasteleman** [comment] 2017-11-28 20:24
I suspect it won't make a difference because the 2 fixes only differ in the devices the fix was implemented. So I suspect I have to mod the dimming code part to fix that one.

**Comment by moekdegroot** [comment] 2017-11-28 20:52
I installed the first fix as well but I can't say anything for sure.
The placing off the powercord and little square box are in a closet with mirrors (which I installed this afternoon) and it totally screws up reception so I will have to reposition it this week.
But I'll take your word for it;)
Ps. I'm assuming the little plastic square box is the zigbee receiving part of the light, right?
So if I place that outside the reception should improve?
![img_0821](https://user-images.githubusercontent.com/16590284/33343622-4bf4b516-d486-11e7-829b-205961ccf98f.JPG)

**Comment by kasteleman** [comment] 2017-11-28 20:57
hmmm, now the flow isn't working at all if I look at the screenshot?
But the rest is working?
Can be, that the switching between the different versions (App Store version and beta branch) screws things up. So if you have the time and willing to test, can you exclude the device and include it again with the latest driver installed?

**Comment by moekdegroot** [comment] 2017-11-28 21:13
Yeah I guess I'm stressing the zigbee part a bit ;)
No it's working off and on.
Homey keeps queing commands and in one of the try's I got this.
But I really think this is because of the mirrors or the mesh.
Before you put any more work in this I would suggest waiting until I remove the pucks from where they are now but I'm afraid that won't be tonight.
My daughter was still sneaking around in her room so I could test upstairs but I'm afraid it's to late now.
I'll try and remove them tomorrow evening.
Thanks for your efforts, much appreciated!

**Comment by kasteleman** [comment] 2017-11-28 21:17
but the flow issue exists for the pucks and the strips, so I don't think that should solve the issue with first going to 100% before adjusting the dim level to for example 25% if the last state was 100% before you switched them to off.

**Comment by moekdegroot** [comment] 2017-11-28 21:29
That's true.
They are 2 different things.
I just wanted to make sure you weren't going on witch hunt trying to solve the screengrab I posted ;)
In that case, please continue 😄 .

**Comment by kasteleman** [comment] 2017-11-29 07:18
Changed the dim part for the Puck in the beta branch. Curious what will be the effect of it.

**Comment by moekdegroot** [comment] 2017-11-29 08:23
Hi Martin,

Just missed your update last night. 
If you are really curious to see if it works and you have the time maybe it’s an idea to apply it to the strip as well?
That way I can test it as soon as I get home tonight because I don’t have to remove the strips for proper testing.

**Comment by kasteleman** [comment] 2017-11-29 08:40
Hi Moek,

Hmm can’t apply it to the strip at this moment, Will do as soon as i’m at home

**Comment by kasteleman** [comment] 2017-11-29 17:28
Hi Moek,

Done

**Comment by moekdegroot** [comment] 2017-11-29 17:49
Hi Martin,
Cool!
Still on my way home but hope to start testing in about 45 min. 
Keep you posted.

**Comment by moekdegroot** [comment] 2017-11-29 19:02
Bad news Martin,
The strip is still dimming in 2 steps.
I removed the strip and de-installed the app, ptp'ed homey and kept it of the juice for 10 minutes, installed your current fix and added the strips to homey.
It does seem to change a lot faster from dimlevel 1 to dimlevel 2 but that could also be because of the ptp off course.
Do you need to know anything else?

**Comment by kasteleman** [comment] 2017-11-29 19:30
the faster dimming is because I set the transition time to 0
check the new commit and the please report back by mail

**Comment by moekdegroot** [comment] 2017-11-29 19:48
Nope sorry, still the 2 steps.
You still feeling up for it?
Maybe you're trying to solve something that can't be fixed...

**Comment by kasteleman** [comment] 2017-11-29 19:53
let me check with a Athom developer. Can take some time.
But the on off is still ok?

**Comment by moekdegroot** [comment] 2017-11-29 19:55
Yep, on/off still going strong!

**Comment by kasteleman** [comment] 2018-01-17 11:36
Fixed in 1.0.7

**Closed by kasteleman** 2018-01-17 11:36 UTC
